### ISSUE TITLE
 Could not find a package configuration file provided by "moveit_msgs"

### ISSUE THREAD

**Issue by tunaonur** [baxter-flowers/human_moveit_config#1]
Hi,
I cloned this into src in my catkin workspace and then I tried catkin_make but it gave me the following error. How can I solve this? Thank you very much! 

-- Could not find the required component 'moveit_msgs'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "moveit_msgs" with
  any of the following names:

```
moveit_msgsConfig.cmake
moveit_msgs-config.cmake
```

  Add the installation prefix of "moveit_msgs" to CMAKE_PREFIX_PATH or set
  "moveit_msgs_DIR" to a directory containing one of the above files.  If
  "moveit_msgs" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  human_moveit_config/CMakeLists.txt:7 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/onurtuna/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/onurtuna/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by ymollard** [comment]
Please install MoveIt from the binaries: http://moveit.ros.org/install/

**Comment by tunaonur** [comment]
It works now! Thanks a lot! @ymollard

**Comment by RuanvanBreda** [comment]
Thanks!

**Comment by pradip-gubhaju** [comment]
thanks alot~! 
from south korea

**Comment by Prakhyath19** [comment]
Thanks man. It helped!
